# Generated by Django 5.1.4 on 2024-12-10 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='absent_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество пропусков'),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('status', models.CharField(choices=[('present', 'Присутствовал'), ('absent', 'Отсутствовал'), ('none', 'Не указано')], default='none', max_length=10, verbose_name='Статус посещения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
